### ISSUE TITLE
Deprecate and archive Kube2pulumi

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/kube2pulumi#117]
Based on issue analysis, we believe https://github.com/pulumi/pulumi-converter-k8s represents a strict improvement over pulumi/kube2pulumi. As a result we should:

```[tasklist]
### Tasks
- [x] add pulumi-converter-k8s to team management and rename to pulumi-converter-kubernetes
- [x] Update the pulumi-converter-k8s with more description and some examples and assert more confidently that it replaces kube2pulumi (can use the current Kube2pulumi README as inspiration)
- [x] Update [CLI docs](https://www.pulumi.com/docs/cli/commands/pulumi_convert/) (https://github.com/pulumi/pulumi/pull/15359)
- [x] Add a deprecation notice to the kube2pulumi README (https://github.com/pulumi/kube2pulumi/pull/118)
- [x] update [Migrating from Kubernetes YAML or Helm Charts | Pulumi Docs](https://www.pulumi.com/docs/using-pulumi/adopting-pulumi/migrating-to-pulumi/from-kubernetes/#converting-kubernetes-yaml) with instructions for the new converter. (https://github.com/pulumi/pulumi-hugo/pull/3903)
- [x] Update [interactive website](https://www.pulumi.com/kube2pulumi/) to use the new converter plugin (https://github.com/pulumi/home/pull/3290)
- [x] Notify our customers of the change via slack
- [x] close remaining issues as won't fix
- [x] archive the repository
- [x] Add a note to the default issue templates to suggest the new converter
```

**Comment by rquitales** [comment]
Note: we will defer the archiving of this repository.
